### ISSUE TITLE
move to TBEP group page?

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/TBEP_Habitat_Restoration#1]
Should we move this repository to the TBEP group page?  Is this going to be the repository where the data are updated annually as the "official" dataset?

**Comment by kflahertywalia** [comment]
I'm good with that especially for this year when the partners will be reporting directly to us. Since this was background data cleaning, should we just migrate the final "clean" dataset, rename, and include metadata? 

We may need to revisit how to update the file each year once we figure out a setup for data entry. There will be a few columns we'll need to resolve from the GPRA finalized database ("View Detail" column) and the additional HMP tracking columns we need (GeneralActivity and GeneralHabitat).

**Comment by fawda123** [comment]
Okay, thanks, let's migrate it over to the TBEP group page.  I think only you can do that since you're the owner - should be under Settings -> General, then "transfer ownership" all the way at the bottom in the danger zone. 

I would keep the background data cleaning info and datasets.  It's not entirely reproducible, but at least demonstrates the process.  

And yes, we'll need to talk about file updating and transfer to Water Atlas.

**Comment by kflahertywalia** [comment]
Looks like it worked. I'll close the issue.
